### ISSUE TITLE
Unable to install pyter with pip

### ISSUE THREAD

**Issue by FabianGroeger96** [aflc/pyter#6]
I'm trying to install `pyter` with pip and it always fails:
```
❯ pip install pyter 
Collecting pyter
  Using cached https://files.pythonhosted.org/packages/d9/13/d0470459d4f409369cb2cd1e0c6384f756a39f8a66d68de5a96b725e3ef3/pyter-0.2.2.1.tar.gz
Collecting distribute
  Using cached https://files.pythonhosted.org/packages/5f/ad/1fde06877a8d7d5c9b60eff7de2d452f639916ae1d48f0b8f97bf97e570a/distribute-0.7.3.zip
    ERROR: Command errored out with exit status 1:
     command: /usr/local/opt/python/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/cg/33bh_4s51wg03gljc_g8h6rr0000gn/T/pip-install-yv_vhip5/distribute/setup.py'"'"'; __file__='"'"'/private/var/folders/cg/33bh_4s51wg03gljc_g8h6rr0000gn/T/pip-install-yv_vhip5/distribute/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/cg/33bh_4s51wg03gljc_g8h6rr0000gn/T/pip-install-yv_vhip5/distribute/pip-egg-info
         cwd: /private/var/folders/cg/33bh_4s51wg03gljc_g8h6rr0000gn/T/pip-install-yv_vhip5/distribute/
    Complete output (15 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/cg/33bh_4s51wg03gljc_g8h6rr0000gn/T/pip-install-yv_vhip5/distribute/setuptools/__init__.py", line 2, in <module>
        from setuptools.extension import Extension, Library
      File "/private/var/folders/cg/33bh_4s51wg03gljc_g8h6rr0000gn/T/pip-install-yv_vhip5/distribute/setuptools/extension.py", line 5, in <module>
        from setuptools.dist import _get_unpatched
      File "/private/var/folders/cg/33bh_4s51wg03gljc_g8h6rr0000gn/T/pip-install-yv_vhip5/distribute/setuptools/dist.py", line 7, in <module>
        from setuptools.command.install import install
      File "/private/var/folders/cg/33bh_4s51wg03gljc_g8h6rr0000gn/T/pip-install-yv_vhip5/distribute/setuptools/command/__init__.py", line 8, in <module>
        from setuptools.command import install_scripts
      File "/private/var/folders/cg/33bh_4s51wg03gljc_g8h6rr0000gn/T/pip-install-yv_vhip5/distribute/setuptools/command/install_scripts.py", line 3, in <module>
        from pkg_resources import Distribution, PathMetadata, ensure_directory
      File "/private/var/folders/cg/33bh_4s51wg03gljc_g8h6rr0000gn/T/pip-install-yv_vhip5/distribute/pkg_resources.py", line 1518, in <module>
        register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
    AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
I already tried to update `setuptools` and `wheel`, but that did not fix the issue. And I also tried to install everything with `sudo`, which didn't make any difference.

**Comment by bricksdont** [comment]
It might be helpful for you to know:
- building and installing `pyter` does not fail, but building/installing `distribute` (a legacy setuptools wrapper). As far as I can see, this package is not needed to compute TER.
- `pyter` seems to be compatible only with Python 2 and older versions of Python 3.X (`setup.py` is not precise enough about which versions of Python 3.X are compatible)

In other words, install like so:

    pip install pyter --no-deps

and use Python 2.X or a rather outdated version of Python 3, my guess would be 3.4 or similar.

**Comment by bricksdont** [comment]
Also, the Pypi version is outdated, but cloning the repository directly without dependencies works fine with any Python 3:

    git clone https://github.com/roy-ht/pyter
    cd pyter
    pip install --no-deps .

```
python
Python 3.7.3 (default, Dec 20 2019, 18:57:59)
>>> import pyter
>>> ref = u'SAUDI ARABIA denied THIS WEEK information published in the AMERICAN new york times'.split()
>>> hyp = u'THIS WEEK THE SAUDIS denied information published in the new york times'.split()
>>> '%.3f' % pyter.ter(hyp, ref)
'0.308'
```

**Comment by bricksdont** [comment]
... finally, TER is about to be added to SacreBLEU:

https://github.com/mjpost/sacrebleu/pull/102

which is currently maintained and compatible with current versions of Python.
